#include "html-player-source.h"
#include <obs-module.h>
#include <windows.h>
#include <winrt/base.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Media.Control.h>
#include <winrt/Windows.Storage.Streams.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <atomic>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <map>
#include <memory>
#include <mutex>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
#include <algorithm>
#include <cctype>
#pragma comment(lib, "ws2_32.lib")
using namespace winrt; using namespace Windows::Media::Control; using namespace Windows::Storage::Streams; namespace fs=std::filesystem;
namespace {
constexpr unsigned short PORT=38765; constexpr int POLL=250; constexpr size_t MAX_FILE=16*1024*1024;
struct State{bool has=false,playing=false;std::string title,artist,album,source,art;double duration=0,position=0;};
struct Inst{std::string id;fs::path root,entry;};
std::mutex sm,im; State state; std::map<std::string,std::weak_ptr<Inst>> insts; std::atomic_bool run=false; SOCKET srv=INVALID_SOCKET; std::thread server_thread,smtc_thread;
const char* SDK=R"JS((()=>{const m=location.pathname.match(/^\/p\/([^/]+)\//),id=m?m[1]:'',o=location.origin,e=o+'/state',v=id?o+'/p/'+id+'/__version':'';let S={hasTrack:false,playing:false,paused:false,stopped:true,title:'',artist:'',album:'',source:'',duration:0,position:0,timestamp:0,albumArt:''},V=null,L=new Map;const emit=(n,x)=>(L.get(n)||[]).forEach(f=>{try{f(x)}catch(_){}}),upd=x=>{const q=S;S=Object.assign({hasTrack:false,playing:false,paused:false,stopped:true,title:'',artist:'',album:'',source:'',duration:0,position:0,timestamp:0,albumArt:''},x||{});if(q.title!==S.title||q.artist!==S.artist||q.album!==S.album||q.source!==S.source)emit('trackchange',S);if(q.playing!==S.playing)emit(S.playing?'play':'pause',S);if(q.hasTrack!==S.hasTrack)emit(S.hasTrack?'trackchange':'stop',S);if(q.albumArt!==S.albumArt)emit('albumart',S.albumArt);emit('state',S)};async function r(){try{let x=await fetch(e+'?t='+Date.now(),{cache:'no-store'});if(x.ok)upd(await x.json())}catch(_){}}async function c(){if(!v)return;try{let x=await fetch(v+'?t='+Date.now(),{cache:'no-store'});if(!x.ok)return;let n=await x.text();if(V!==null&&n!==V)location.reload();V=n}catch(_){}}function loop(){r().finally(()=>setTimeout(loop,250))}function vl(){c().finally(()=>setTimeout(vl,1000))}window.obsPlayer={get state(){return S},get playerId(){return id},get endpoint(){return e},on(n,f){if(!L.has(n))L.set(n,new Set);L.get(n).add(f);return()=>L.get(n)?.delete(f)},once(n,f){let x=this.on(n,y=>{x();f(y)});return x},refresh:r,getProgress(){return S.duration?Math.max(0,Math.min(1,S.position/S.duration)):0},getPosition(){if(!S.playing||!S.timestamp)return S.position;let n=performance.timeOrigin/1000+performance.now()/1000;return Math.max(0,Math.min(S.duration||Infinity,S.position+n-S.timestamp))}};window.OBSPlayer=window.obsPlayer;emit('ready',S);loop();vl()})();)JS";
std::string esc(const std::string&s){std::ostringstream o;for(unsigned char c:s){switch(c){case'"':o<<"\\\"";break;case'\\':o<<"\\\\";break;case'\n':o<<"\\n";break;case'\r':o<<"\\r";break;case'\t':o<<"\\t";break;default:if(c<32)o<<"\\u"<<std::hex<<std::setw(4)<<std::setfill('0')<<(int)c;else o<<c;}}return o.str();}
std::string b64(const uint8_t*d,size_t n){static const char*t="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";std::string o;o.reserve((n+2)/3*4);for(size_t i=0;i<n;i+=3){uint32_t v=uint32_t(d[i])<<16;if(i+1<n)v|=uint32_t(d[i+1])<<8;if(i+2<n)v|=d[i+2];o+=t[v>>18&63];o+=t[v>>12&63];o+=i+1<n?t[v>>6&63]:'=';o+=i+2<n?t[v&63]:'=';}return o;}
std::string amime(const std::string&s){if(s=="image/png")return"image/png";if(s=="image/webp")return"image/webp";if(s=="image/gif")return"image/gif";return"image/jpeg";}
void smtc_loop(){try{init_apartment(apartment_type::multi_threaded);auto mgr=GlobalSystemMediaTransportControlsSessionManager::RequestAsync().get();while(run){State n;try{auto ss=mgr.GetSessions();GlobalSystemMediaTransportControlsSession s=nullptr;for(uint32_t i=0;i<ss.Size();++i){auto x=ss.GetAt(i),id=to_string(x.SourceAppUserModelId());if(id.find("spotify")!=std::string::npos||id.find("youtube")!=std::string::npos||id.find("ytm")!=std::string::npos||id.find("applemusic")!=std::string::npos||id.find("cider")!=std::string::npos||id.find("vlc")!=std::string::npos||id.find("chrome")!=std::string::npos||id.find("msedge")!=std::string::npos||id.find("firefox")!=std::string::npos||id.find("opera")!=std::string::npos||id.find("brave")!=std::string::npos){s=x;break;}}if(s){auto p=s.TryGetMediaPropertiesAsync().get(),t=s.GetTimelineProperties(),b=s.GetPlaybackInfo();if(p&&b){n.has=true;n.playing=b.PlaybackStatus()==GlobalSystemMediaTransportControlsSessionPlaybackStatus::Playing;n.title=to_string(p.Title());n.artist=to_string(p.Artist());n.album=to_string(p.AlbumTitle());n.source=to_string(s.SourceAppUserModelId());n.duration=std::max(0.0,std::chrono::duration<double>(t.EndTime()-t.StartTime()).count());n.position=std::max(0.0,std::chrono::duration<double>(t.Position()).count());auto th=p.Thumbnail();if(th){auto st=th.OpenReadAsync().get();uint32_t z=(uint32_t)st.Size();if(z&&z<MAX_FILE){DataReader r(st);r.LoadAsync(z).get();std::vector<uint8_t>x(z);r.ReadBytes(array_view<uint8_t>(x.data(),x.data()+z));n.art="data:"+amime(to_string(st.ContentType()))+";base64,"+b64(x.data(),x.size());}}}}}catch(...){ }{std::lock_guard<std::mutex>l(sm);state=std::move(n);}std::this_thread::sleep_for(std::chrono::milliseconds(POLL));}uninit_apartment();}catch(...){blog(LOG_ERROR,"[obs-html-player] SMTC initialization failed");}}
std::string json(){std::lock_guard<std::mutex>l(sm);double now=std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();std::ostringstream o;o<<"{\"hasTrack\":"<<(state.has?"true":"false")<<",\"playing\":"<<(state.playing?"true":"false")<<",\"paused\":"<<(!state.playing&&state.has?"true":"false")<<",\"stopped\":"<<(!state.has?"true":"false")<<",\"title\":\""<<esc(state.title)<<"\",\"artist\":\""<<esc(state.artist)<<"\",\"album\":\""<<esc(state.album)<<"\",\"source\":\""<<esc(state.source)<<"\",\"duration\":"<<state.duration<<",\"position\":"<<state.position<<",\"timestamp\":"<<now<<",\"albumArt\":\""<<esc(state.art)<<"\"}";return o.str();}
std::string dec(std::string s){std::string o;for(size_t i=0;i<s.size();++i){if(s[i]=='%'&&i+2<s.size()){auto h=[](char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return-1;};int a=h(s[i+1]),b=h(s[i+2]);if(a>=0&&b>=0){o.push_back(char(a*16+b));i+=2;continue;}}o.push_back(s[i]);}return o;}
bool safe(const fs::path&r,const fs::path&q,fs::path&o){try{auto a=fs::weakly_canonical(r),b=fs::weakly_canonical(r/q);auto x=a.native(),y=b.native();if(y.size()<x.size()||y.compare(0,x.size(),x)!=0||(y.size()>x.size()&&y[x.size()]!=fs::path::preferred_separator))return false;o=b;return true;}catch(...){return false;}}
std::string type(const fs::path&p){auto e=p.extension().string();std::transform(e.begin(),e.end(),e.begin(),[](unsigned char c){return(char)std::tolower(c);});if(e==".html"||e==".htm")return"text/html; charset=utf-8";if(e==".css")return"text/css; charset=utf-8";if(e==".js"||e==".mjs")return"application/javascript; charset=utf-8";if(e==".json")return"application/json; charset=utf-8";if(e==".svg")return"image/svg+xml";if(e==".png")return"image/png";if(e==".jpg"||e==".jpeg")return"image/jpeg";if(e==".webp")return"image/webp";if(e==".gif")return"image/gif";if(e==".ico")return"image/x-icon";if(e==".woff")return"font/woff";if(e==".woff2")return"font/woff2";if(e==".ttf")return"font/ttf";if(e==".otf")return"font/otf";return"application/octet-stream";}
void send(SOCKET s,int code,const std::string&b,const char*t){const char*m=code==200?"OK":code==403?"Forbidden":code==404?"Not Found":"Bad Request";std::ostringstream h;h<<"HTTP/1.1 "<<code<<" "<<m<<"\r\nContent-Type: "<<t<<"\r\nAccess-Control-Allow-Origin: *\r\nCache-Control: no-store\r\nContent-Length: "<<b.size()<<"\r\nConnection: close\r\n\r\n";auto x=h.str();::send(s,x.data(),(int)x.size(),0);if(!b.empty())::send(s,b.data(),(int)b.size(),0);}
void file(SOCKET s,const fs::path&p,bool html){std::ifstream f(p,std::ios::binary);if(!f){send(s,404,"Not Found","text/plain");return;}auto z=fs::file_size(p);if(z>MAX_FILE){send(s,403,"File too large","text/plain");return;}std::string b((std::istreambuf_iterator<char>(f)),{});if(html){std::string x="<script src=\"/obs-player.js\"></script><style>html,body{margin:0;background:transparent}</style>";auto i=b.find("</head>");if(i==std::string::npos)b=x+b;else b.insert(i,x);}send(s,200,b,type(p).c_str());}
std::shared_ptr<Inst> get(const std::string&id){std::lock_guard<std::mutex>l(im);auto x=insts.find(id);if(x==insts.end())return{};auto p=x->second.lock();if(!p)insts.erase(x);return p;}
void server_loop(){while(run){sockaddr_in a{};int al=sizeof(a);SOCKET c=accept(srv,(sockaddr*)&a,&al);if(c==INVALID_SOCKET)continue;char buf[8192]{};int n=recv(c,buf,sizeof(buf)-1,0);if(n>0){std::string q(buf,n),line=q.substr(0,q.find("\r\n"));if(line.rfind("GET ",0)!=0){send(c,400,"Bad Request","text/plain");closesocket(c);continue;}auto p=line.find(' ',4);std::string u=line.substr(4,p-4),path=u.substr(0,u.find('?'));if(path=="/state")send(c,200,json(),"application/json; charset=utf-8");else if(path=="/obs-player.js")send(c,200,SDK,"application/javascript; charset=utf-8");else if(path=="/ping")send(c,200,"{\"ok\":true}","application/json");else if(path.rfind("/p/",0)==0){auto z=path.find('/',3);if(z==std::string::npos){send(c,404,"Not Found","text/plain");}else{auto in=get(path.substr(3,z-3));if(!in){send(c,404,"Not Found","text/plain");}else{auto rel=dec(path.substr(z+1));if(rel=="__version"){try{send(c,200,std::to_string(fs::last_write_time(in->entry).time_since_epoch().count()),"text/plain");}catch(...){send(c,404,"Not Found","text/plain");}}else{if(rel.empty())rel=in->entry.filename().string();fs::path out;if(!safe(in->root,fs::path(rel),out)||!fs::is_regular_file(out)){send(c,404,"Not Found","text/plain");}else{auto e=out.extension().string();std::transform(e.begin(),e.end(),e.begin(),[](unsigned char x){return(char)std::tolower(x);});file(c,out,e==".html"||e==".htm");}}}}}}else send(c,404,"Not Found","text/plain");}closesocket(c);}}
void start(){if(run.exchange(true))return;WSADATA w{};if(WSAStartup(MAKEWORD(2,2),&w)!=0){run=false;return;}srv=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(PORT);inet_pton(AF_INET,"127.0.0.1",&a.sin_addr);if(srv==INVALID_SOCKET||bind(srv,(sockaddr*)&a,sizeof(a))||listen(srv,16)){if(srv!=INVALID_SOCKET)closesocket(srv);srv=INVALID_SOCKET;run=false;WSACleanup();blog(LOG_ERROR,"[obs-html-player] local server bind failed");return;}server_thread=std::thread(server_loop);smtc_thread=std::thread(smtc_loop);}
void stop(){if(!run.exchange(false))return;if(srv!=INVALID_SOCKET){shutdown(srv,SD_BOTH);closesocket(srv);srv=INVALID_SOCKET;}if(server_thread.joinable())server_thread.join();if(smtc_thread.joinable())smtc_thread.join();std::lock_guard<std::mutex>l(im);insts.clear();WSACleanup();}
struct Source{obs_source_t*src=nullptr;obs_source_t*browser=nullptr;std::shared_ptr<Inst>inst;int w=800,h=250;};
std::string id(obs_source_t*s){std::ostringstream o;o<<std::hex<<(uintptr_t)s;return o.str();}
void rebuild(Source*s,obs_data_t*d){const char*f=obs_data_get_string(d,"local_file");if(!f||!*f)return;fs::path e;try{e=fs::weakly_canonical(f);if(!fs::is_regular_file(e))return;}catch(...){return;}auto in=std::make_shared<Inst>();in->id=id(s->src);in->entry=e;in->root=e.parent_path();{std::lock_guard<std::mutex>l(im);insts[in->id]=in;}obs_data_t*b=obs_data_create();std::string url="http://127.0.0.1:"+std::to_string(PORT)+"/p/"+in->id+"/";obs_data_set_bool(b,"is_local_file",false);obs_data_set_string(b,"url",url.c_str());obs_data_set_int(b,"width",obs_data_get_int(d,"width"));obs_data_set_int(b,"height",obs_data_get_int(d,"height"));obs_data_set_int(b,"fps_num",obs_data_get_int(d,"fps_num"));obs_data_set_int(b,"fps_den",1);obs_data_set_bool(b,"shutdown",obs_data_get_bool(d,"shutdown"));obs_data_set_bool(b,"reroute_audio",false);obs_data_set_string(b,"css","html,body{margin:0;background:transparent;}");auto nb=obs_source_create_private("browser_source","HTML Player Browser",b);obs_data_release(b);if(!nb){std::lock_guard<std::mutex>l(im);insts.erase(in->id);blog(LOG_ERROR,"[obs-html-player] browser_source unavailable");return;}if(s->browser){obs_source_remove_active_child(s->src,s->browser);obs_source_release(s->browser);}s->browser=nb;s->inst=in;obs_source_add_active_child(s->src,s->browser);}
void*create(obs_data_t*d,obs_source_t*x){auto*s=new Source;s->src=x;s->w=(int)obs_data_get_int(d,"width");s->h=(int)obs_data_get_int(d,"height");start();rebuild(s,d);return s;}void destroy(void*p){auto*s=(Source*)p;if(s->browser){obs_source_remove_active_child(s->src,s->browser);obs_source_release(s->browser);}if(s->inst){std::lock_guard<std::mutex>l(im);insts.erase(s->inst->id);}delete s;}void update(void*p,obs_data_t*d){auto*s=(Source*)p;s->w=(int)obs_data_get_int(d,"width");s->h=(int)obs_data_get_int(d,"height");rebuild(s,d);}uint32_t width(void*p){return((Source*)p)->w;}uint32_t height(void*p){return((Source*)p)->h;}void render(void*p,gs_effect_t*){auto*s=(Source*)p;if(s->browser)obs_source_video_render(s->browser);}obs_properties_t*props(void*){auto*p=obs_properties_create();obs_properties_add_path(p,"local_file","HTML 文件",OBS_PATH_FILE,"HTML (*.html;*.htm)",nullptr);obs_properties_add_int(p,"width","宽度",1,7680,1);obs_properties_add_int(p,"height","高度",1,7680,1);obs_properties_add_int(p,"fps_num","FPS",1,120,1);obs_properties_add_bool(p,"shutdown","隐藏时关闭页面");return p;}void defaults(obs_data_t*d){obs_data_set_default_int(d,"width",800);obs_data_set_default_int(d,"height",250);obs_data_set_default_int(d,"fps_num",60);obs_data_set_default_bool(d,"shutdown",false);}const char*name(void*){return"HTML Now Playing";}obs_source_info info{};
}
extern "C" void html_source_register(){info.id="html_now_playing_source";info.type=OBS_SOURCE_TYPE_INPUT;info.output_flags=OBS_SOURCE_VIDEO;info.get_name=name;info.create=create;info.destroy=destroy;info.update=update;info.get_width=width;info.get_height=height;info.get_properties=props;info.get_defaults=defaults;info.video_render=render;obs_register_source(&info);}extern "C" void html_source_unregister(){stop();}
